# Generated by Django 4.0.8 on 2022-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was las modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='Hotspot ID')),
                ('program', models.CharField(max_length=60, verbose_name='Program')),
                ('installed_date', models.DateField(verbose_name='Installed date')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('long', models.FloatField(verbose_name='Longitude')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('mayoralty', models.CharField(max_length=100, verbose_name='Mayoralty')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
